#spring.application.name=demo
#spring.datasource.url=jdbc:mysql://localhost:3306/music_test?characterEncoding=UTF-8&serverTimezone=asia/seoul
#spring.datasource.username=root
#spring.datasource.password=1234

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/music_test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

mybatis:
  config-location: classpath:mybatis/config/config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
